version: '3.7'

services:
  shop_backend:
    container_name: shop_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shop_network

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shop_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shop_network

networks:
  shop_network:
    driver: bridge

volumes:
  pgdata:
